development:
  adapter: postgresql
  encoding: unicode
  database: training_development
  pool: 5
  timeout: 5000
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: training_test
  pool: 5
  timeout: 5000
  username: postgres
  password: